### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by xeridea** [atom/git-diff#85]
Plugin flat out does not work.  No lines are highlighted.  Win7.  Tried restarting, and multiple projects.  Have TortoiseGit installed if that makes a difference.  I see modified files highlighted, but not lines.  Works on Win10 laptop.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* When you open Atom are you opening the root of the Git repository?
* Is the directory you're opening a Git repository?

**Comment by xeridea** [comment]
Version 1.4.3
I can reproduce in safe mode
The project folder added is the root of a git repository.
Went through the debugging document.

**Comment by DylanWalseth** [comment]
I have actually just recently just started getting this issue also. I ran in safe mode and was able to reproduce. Or at least I think it is the same issue.

The file status for change does not update until Atom window loses focus, even on save. I am also running Windows 7, Atom version 1.5.0. .git folder is at root.

Even when the file is marked as have diffs, I run the toggle diffs command and it says their are no differences even though I know there is (checking git diff) and it does not mark the line in the gutter.

Made a quick video to show what I am talking about
https://youtu.be/8FDo9dnC9M0

**Comment by Fishrock123** [comment]
Atom version 1.5.3. Just started experiencing this today.

Works under `atom --safe`.

> When you open Atom are you opening the root of the Git repository?

Yes. `atom .`

> Is the directory you're opening a Git repository?

Absolutely.

ping @lee-dohm 

I use the Seti theme by default but changing it does not appear to help. This only shows up in safe mode.


Considering I work in a very large project this plugin is extremely important to me. :heart:

**Comment by lee-dohm** [comment]
@Fishrock123 Are you also on Windows 7?

**Comment by Fishrock123** [comment]
@lee-dohm Nope, OS X 10.10.5 (14F1605)

**Comment by 50Wliu** [comment]
For anyone experiencing this issue: if you open up the dev tools (Cmd+Shift+I or Ctrl+Alt+I), are there any errors relating to git-diff in the console?

**Comment by Fishrock123** [comment]
@50Wliu No errors.

**Comment by lee-dohm** [comment]
@Fishrock123 What does this mean?

> Works under atom --safe.

Does it mean that things work as expected? Or that the bug reproduces?

**Comment by Fishrock123** [comment]
@lee-dohm The icons appear in the gutter under `--safe` mode. They do not appear when I regularly launch atom (`atom .`).

**Comment by lee-dohm** [comment]
@Fishrock123 That sounds like one of the community packages you have installed is causing the problem. People have reported having success using the [package-cop package](https://atom.io/packages/package-cop) to track down offending packages.

**Comment by Fishrock123** [comment]
Update: removing the git-diff v1.0.0 (Community Package one) resolves the issue.

**Comment by lee-dohm** [comment]
Glad it is fixed for you @Fishrock123 :grinning:

**Comment by DylanWalseth** [comment]
Just an update, haven't responded in a few days.

Updated my Atom to version 1.5.3 (and still on Win 7)
Still have the issue.
I run the "toggle diff list" command and it says no diffs, even if the file in the tree view is showing as changed and the git status/diff through terminal shows the diffs correctly.

Behavior matches exactly as stated in my previous post.

This still happens even with all community packages disabled, run in --safe

No errors in my console (at least relating to git-diff). @50Wliu 

Package works as expected on both of my other machines
Win 7 and Win 10

Packages are mostly the same across all three, I honestly have no idea what could be causing this issue, sorry for being so unhelpful in finding the root of this issue. I'm avoiding fresh installing in hopes to locate the cause if you have any suggestions on where I should check.

**Comment by DylanWalseth** [comment]
Interestingly enough, it appears the bug only occurs if the repo is in my Desktop folder, but not if it somewhere else. I think xeridea's reply is on to something with the symlinks.

**Comment by nils-werner** [comment]
@Fishrock123 I have the same problem with the same two packages on the exact same versions. How did you manage to uninstall the community package? And why did you uninstall the 1.0.0 one and not 0.57.0?

**Comment by DavidCai1993** [comment]
@nils-werner It works!

**Comment by sgt39007** [comment]
just remove git-diff from ~./atom/package  i had tested...it works

**Comment by puranjayjain** [comment]
Atom: 1.7.4
OS: Windows 10 x64 Enterprise
I have recently started facing this bug where the line markers are gone but only for files which either have Folders or Files in path which begin with a capital letter. e.g the bug occurs on "Foo" but not
on "foo".

**Comment by Mouvedia** [comment]
> Do symlinks affect it?

#91?

**Comment by nibudd** [comment]
I'd to confirm. I had the same issue of not seeing git indicators in the gutter. Removing the community git-diff package (apm uninstall git-diff) did the trick.

**Comment by sharifzadesina** [comment]
Dosn't work for me too,
ArchLinux
Atom 1.12.9
![screenshot from 2017-01-06 19-56-55](https://cloud.githubusercontent.com/assets/15300551/21724720/c9928ada-d44a-11e6-965d-da29dde5a66b.png)

**Comment by sharifzadesina** [comment]
still doesn't work and there is no local package.

**Comment by sharifzadesina** [comment]
Guys I have discovered the problem! it was cause of my Synatx them... I have changed it to "One Light" and it is ok now.

**Comment by techgnosis** [comment]
Broken in 1.15.0 for me too. I don't have any non-stock packages installed. Doesn't work for any language in any UI or Syntax theme.

**Comment by JordiPiqueras** [comment]
![image](https://cloud.githubusercontent.com/assets/7103591/25123707/a692a360-2429-11e7-95b9-29435f6fd6e7.png)
The screen is crushed horizontally, how can i solve it!

For other hand I have problems with bitbucket/git, not rules commands alt-b, how can i fix it?

**Comment by Ben3eeE** [comment]
@Encr1pt3d https://discuss.atom.io/t/where-did-this-empty-space-come-from-how-do-i-get-rid-of-it/30226

For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Ben3eeE** [comment]
I am optimistically closing this issue since all the reports for this issue seems to have been resolved by various things :crossed_fingers: 

* Uninstalling `git-diff` when it was installed as a community package. `apm uninstall git-diff`
* Changing to a different UI/Syntax theme
* Running Atom in safe mode `atom --safe`
* Ensuring that you have the `.git` folder in the top level https://github.com/atom/atom/issues/2203

If you still encounter this issue even when trying all the above suggestions then please open a new issue and completely fill out the provided issue template.

**Comment by cataline** [comment]
Deleting the repo and cloning it again is the only thing that worked for me.

**Comment by 1c7** [comment]
2018-5-14
remove git-diff from `~/.atom/packages` using `rm -rf git-diff` work for me
after that I switch back to Atom editor
![image](https://user-images.githubusercontent.com/1804755/39993764-91b09a42-57a9-11e8-88b5-1adf9c0289d9.png)
it work again, new line have green color indicate that
